/*
  config.h - Configs and MACROs
  Created by Cyrill Lippuner, 2019.
*/
#ifndef Config_h
#define Config_h

#include "Arduino.h"

/**
 * MACROS
 */

/* The unique ID of the robot */
#define ROBOT_ID 1

/* Serial communication */
#define SERIAL_ENABLE
#define SERIAL_BAUD_RATE 115200

/* Timings */
#define SENSOR_PROXIMITY_HORIZONAL_PERIOD 10 // ms
#define SENSOR_PROXIMITY_VERTICAL_PERIOD 10 // ms
#define SENSOR_PROXIMITY_DETECT_PERIOD 10 // ms
#define SENSOR_TIME_OF_FLIGHT_PERIOD 100 // ms
#define SENSORS_PERIOD 100 // ms
#define CONTROLLER_PERIOD 100 // ms

/* Thresholds */
#define THRESHOLD_HORIZONTAL_PROXIMITY 60
#define THRESHOLD_DISTANCE_TIME_OF_FLIGHT 50

/* Sensors */
#define SENSOR_PROXIMITY_HORIZONTAL_OFFSET 0
#define SENSOR_PROXIMITY_HORIZONTAL_COUNT 6
#define SENSOR_PROXIMITY_VERTICAL_OFFSET 6
#define SENSOR_PROXIMITY_VERTICAL_COUNT 2
#define SENSOR_PROXIMITY_DETECT_OFFSET 8
#define SENSOR_PROXIMITY_DETECT_COUNT 2

#define SENSOR_PROXIMITY_RIGHT 0
#define SENSOR_PROXIMITY_FORWARD_RIGHT 1
#define SENSOR_PROXIMITY_FORWARD 2
#define SENSOR_PROXIMITY_FORWARD_LEFT 3
#define SENSOR_PROXIMITY_LEFT 4
#define SENSOR_PROXIMITY_BACKWARD 5
#define SENSOR_PROXIMITY_DOWN_LEFT 0
#define SENSOR_PROXIMITY_DOWN_RIGHT 1
#define SENSOR_PROXIMITY_DETECT_LEFT 0
#define SENSOR_PROXIMITY_DETECT_RIGHT 1

#define SENSOR_TIME_OF_FLIGHT_COUNT 1

#define SENSOR_TIME_OF_FLIGHT_RIGHT 0
#define SENSOR_TIME_OF_FLIGHT_CENTER 1
#define SENSOR_TIME_OF_FLIGHT_LEFT 2

/* PINs */
#define TESTLED 13
#define SENSOR_PROXIMITY_RIGHT_PIN A0
#define SENSOR_PROXIMITY_FORWARD_RIGHT_PIN A1
#define SENSOR_PROXIMITY_FORWARD_PIN A2
#define SENSOR_PROXIMITY_FORWARD_LEFT_PIN A3
#define SENSOR_PROXIMITY_LEFT_PIN A4
#define SENSOR_PROXIMITY_BACKWARD_PIN A5
#define SENSOR_PROXIMITY_DOWN_LEFT_PIN A6
#define SENSOR_PROXIMITY_DOWN_RIGHT_PIN A7
#define SENSOR_PROXIMITY_DETECT_LEFT_PIN A8
#define SENSOR_PROXIMITY_DETECT_RIGHT_PIN A9

#define SENSOR_TIME_OF_FLIGHT_RIGHT_PIN_TRIGGER 52
#define SENSOR_TIME_OF_FLIGHT_RIGHT_PIN_ECHO 53
#define SENSOR_TIME_OF_FLIGHT_LEFT_PIN_TRIGGER 54
#define SENSOR_TIME_OF_FLIGHT_LEFT_PIN_ECHO 55

/**
 * The possible states of the robot can have
 */
enum State
{
  s_initialize,       // Initialization state, only active during set up
  s_run,
  s_turn,
  s_wait,
  s_panic             // Panic state, when something unexpected happened
};


#endif
