/*
  config.h - Configs and MACROs
  Created by Cyrill Lippuner, 2019.
*/
#ifndef Config_h
#define Config_h

// Constants
#define M_PI 3.141592653589793238462643


/**
 * MACROS
 */

/* The unique ID of the robot */
#define ROBOT_ID 1

/* Serial communication */
#define SERIAL_ENABLE 1
#define SERIAL_BAUD_RATE 19200

/* Timings */
#define SENSOR_PROXIMITY_FREQUENCY 10 // ms
#define SENSORS_FREQUENCY 100 // ms
#define CONTROLLER_FREQUENCY 100 // ms

/* Sensors */
#define SENSOR_PROXIMITY_COUNT 10
#define SENSOR_PROXIMITY_CALIBRATION_COUNT 10
#define SENSOR_PROXIMITY_MEASUREMENT_COUNT 8
#define SENSOR_PROXIMITY_THRESHOLD 400
#define SENSOR_PROXIMITY_RIGHT 0
#define SENSOR_PROXIMITY_FORWARD_RIGHT 1
#define SENSOR_PROXIMITY_FORWARD 2
#define SENSOR_PROXIMITY_FORWARD_LEFT 3
#define SENSOR_PROXIMITY_LEFT 4
#define SENSOR_PROXIMITY_BACKWARD 5
#define SENSOR_PROXIMITY_DOWN_RIGHT 6
#define SENSOR_PROXIMITY_DOWN_LEFT 7
#define SENSOR_PROXIMITY_DETECT_RIGHT 8
#define SENSOR_PROXIMITY_DETECT_LEFT 9

#define SENSOR_TOF_COUNT 3
#define SENSOR_TOF_TIMEOUT 4000 // us
#define SENSOR_TOF_CONVERTION_FACTOR 29.1
#define SENSOR_TOF_MEASUREMENT_COUNT 5
#define SENSOR_TOF_RIGHT 0
#define SENSOR_CENTER_RIGHT 1
#define SENSOR_RIGHT_RIGHT 2

#define SENSOR_IMU_COUNT 1

#define SENSOR_IMU_MEASUREMENT_DIMENSIONS 3
#define SENSOR_IMU_MEASUREMENT_COUNT 12
#define SENSOR_IMU_Z_ORIENTATION_THRESHOLD 10.f
#define SENSOR_IMU_YAW 0
#define SENSOR_IMU_PITCH 1
#define SENSOR_IMU_ROLL 2


#define BTN_COUNT 3
#define BTN_RESET 0
#define BTN_START 1
#define BTN_PAUSE 2

#define LED_COUNT 2
#define LED_SYSTEM 0
#define LED_RUNNING 1

#define ACTUATOR_MOTOR_COUNT 2
#define ACTUATOR_MOTOR_RIGHT 0
#define ACTUATOR_MOTOR_LEFT 1
// [0,200] -> [A, B] (m/s)
#define ACTUATOR_MOTOR_SPEED_BOUNDS_A 0
#define ACTUATOR_MOTOR_SPEED_BOUNDS_B 255
#define ACTUATOR_MOTOR_ENCODER_RESOLUTION 24
#define ACTUATOR_MOTOR_TRANSMISSION 75
#define ACTUATOR_MOTOR_DIAMETER 0.24f // m/s
#define ACTUATOR_MOTOR_PID_KP 200.f
#define ACTUATOR_MOTOR_PID_KI 100.f
#define ACTUATOR_MOTOR_PID_KD 10.f

#define ACTUATOR_SERVO_COUNT 1
#define ACTUATOR_SERVO_BAR_RIGHT 0
#define ACTUATOR_SERVO_BAR_LEFT 1

#define ACTUATOR_SERVO_BAR_RIGHT_OPEN 160
#define ACTUATOR_SERVO_BAR_RIGHT_CLOSED 20
#define ACTUATOR_SERVO_BAR_LEFT_OPEN 160
#define ACTUATOR_SERVO_BAR_LEFT_CLOSED 20


/* PINs */
#define TESTLED 13
#define SENSOR_PROXIMITY_RIGHT_PIN A0
#define SENSOR_PROXIMITY_FORWARD_RIGHT_PIN A1
#define SENSOR_PROXIMITY_FORWARD_PIN A2
#define SENSOR_PROXIMITY_FORWARD_LEFT_PIN A3
#define SENSOR_PROXIMITY_LEFT_PIN A4
#define SENSOR_PROXIMITY_BACKWARD_PIN A5
#define SENSOR_PROXIMITY_DOWN_RIGHT_PIN A6
#define SENSOR_PROXIMITY_DOWN_LEFT_PIN A7
#define SENSOR_PROXIMITY_DETECT_RIGHT_PIN A8
#define SENSOR_PROXIMITY_DETECT_LEFT_PIN A9

#define SENSOR_TOF_RIGHT_TRIGGER_PIN 52
#define SENSOR_TOF_RIGHT_ECHO_PIN 53
#define SENSOR_TOF_CENTER_TRIGGER_PIN 54
#define SENSOR_TOF_CENTER_ECHO_PIN 55
#define SENSOR_TOF_LEFT_TRIGGER_PIN 56
#define SENSOR_TOF_LEFT_ECHO_PIN 57

#define SENSOR_IMU_SDA_PIN 20
#define SENSOR_IMU_SCL_PIN 21
#define SENSOR_IMU_INT_PIN 2

#define GLOBAL_PAUSE_BTN 22
#define GLOBAL_PAUSE_LED 10

#define BTN_START_PIN 23

#define LED_SYSTEM_PIN 30
#define LED_RUNNING_PIN 31

#define ACTUATOR_MOTOR_RIGHT_DIRECTION_PIN 4
#define ACTUATOR_MOTOR_RIGHT_SPEED_PIN 5
#define ACTUATOR_MOTOR_RIGHT_INT_PIN 3
#define ACTUATOR_MOTOR_LEFT_DIRECTION_PIN 7
#define ACTUATOR_MOTOR_LEFT_SPEED_PIN 6
#define ACTUATOR_MOTOR_LEFT_INT_PIN 19

#define ACTUATOR_SERVO_BAR_RIGHT_PIN 11
#define ACTUATOR_SERVO_BAR_LEFT_PIN 12



/**
 * The possible states of the robot can have
 */
enum State
{
  s_initialization,       // Initialization state, only active during set up
  s_calibration,          // Calibrate all sensors and actuators
  s_idle,                 // Idle state, waiting for start
  s_test,                 // Testing state
  s_run,
  s_turn,
  s_wait,
  s_panic             // Panic state, when something unexpected happened
};


#endif
